---
name: Gradle

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [11, 17, 21]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_commands: --stacktrace build
      ArtifactoryUserName: ${{ secrets.JENKINS_USERNAME }}
      ArtifactoryPassword: ${{ secrets.JENKINS_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Install dependency
        run: sudo apt-get install libblosc1
      - name: Checkout zarr-java
        uses: actions/checkout@v4
        with:
          repository: zarr-developers/zarr-java
          path: zarr-java
      - name: Build and install zarr-java
        run: |
          cd zarr-java
          mvn clean install -DskipTests -Dgpg.skip=true
          cd ..
      - name: Run commands
        run: |
          ./gradlew ${{ env.gradle_commands }}
          cp build/libs/*.jar build/
      - name: Get dependencies
        if: matrix.java == 11
        run: |
          ./gradlew copyDependencies
          cp -v build/libs/*.jar libs/
      - name: Upload artifacts
        if: matrix.java == 11
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            libs/*.jar
            build/*.jar
